# Generated by Django 4.1.2 on 2023-06-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marggis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
