# Generated by Django 4.1.2 on 2023-06-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marggis', '0004_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
